aws_dbt_snowflake_project:
  outputs:
    dev:
      account: NWKBACH-SS20990
      database: AIRBNB
      password: Gagn@3020010699
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: Gagn20
      warehouse: COMPUTE_WH
  target: dev
